apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-v-argo
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: ocp-v/
    repoURL: 'https://github.com/leo-puh/gitops-cluster-mgmt-sandbox'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
